spring.application.name=travelx
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:mysql://5.tcp.ngrok.io:29865/base54
spring.datasource.username=estudiantedes3
spring.datasource.password=desarrollo2026$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
server.port=8081


rapidapi.visa.host=visa-requirement.p.rapidapi.com
rapidapi.visa.key=0fc49bd599mshf649d0c7e9dc83ap112f8djsn05dad008a684

rapidapi.hotels.host=hotels4.p.rapidapi.com
rapidapi.hotels.key=0fc49bd599mshf649d0c7e9dc83ap112f8djsn05dad008a684

rapidapi.airbnb.host=airbnb19.p.rapidapi.com
rapidapi.airbnb.key=0fc49bd599mshf649d0c7e9dc83ap112f8djsn05dad008a684

rapidapi.googleflights.host=google-flights2.p.rapidapi.com
rapidapi.googleflights.key=90dcb39f12mshbb30af3fc94fb7ap1e4174jsnba49a0461718


# Configuracion de correo - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pipezam200521@gmail.com
spring.mail.password=vrjaapunjflzzhgm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
# Configuracion de Swagger
springdoc.swagger-ui.path=/
springdoc.swagger-ui.docExpansion=none
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.syntaxHighlight.theme=markdown
springdoc.swagger-ui.displayRequestDuration=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.supportedSubmitMethods=["get","post","put","delete"]
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.html-escaping.enabled=false